### ISSUE TITLE
[preview] ls結果はbasenameで出力する

### ISSUE THREAD

**Issue by yamamoto-yuta** [ShotaroKataoka/Fuzzy-Terminal-Explorer#19]

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
lsってpreviewの上のやつのこと？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
それです．微妙に表示方法の違いが出ていて気になった感じです．
![image](https://user-images.githubusercontent.com/55144709/99206805-a4cd6500-27ff-11eb-996d-884ec8887e78.png)
![image](https://user-images.githubusercontent.com/55144709/99206847-bf9fd980-27ff-11eb-9b1e-abb31997474a.png)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
表示の違いがいまいちわからない．．．
ls -l の下側にラインがないみたいなことかな？

あとこれの再現方法が分からないので状況教えてもらえると嬉しいです！

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
ls表示部が微妙に安定してないところがあるので，後で画像付きで送ります

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
previewをスクロールさせてみたんですが，ターミナルのウィンドウサイズ等によってls表示部が区切り線の上に上書きされていたりいなかったりするようです

![test](https://user-images.githubusercontent.com/55144709/99210036-072a6380-2808-11eb-8987-1c13fc49f4b9.gif)

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
![issue19](https://user-images.githubusercontent.com/42331656/99210503-4efdba80-2809-11eb-8cdf-c47c34ca47db.gif)

こっちの環境だと再現できてなさそう．．．？

**Comment by ShotaroKataoka** [comment]
`extensions.setting` のファイルでも確認したけどチカチカしたりしない

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
dev/v0.0.1/issue19-previewブランチpullしてみて
どんな感じ？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
大半のファイルはls結果部が２行になってる（echoの影響）んですが，一部ファイルは↓みたいになってますね…

![image](https://user-images.githubusercontent.com/55144709/99215551-9a6a9580-2816-11eb-9e43-4190f55b21ea.png)
![image](https://user-images.githubusercontent.com/55144709/99215558-a0f90d00-2816-11eb-915c-99fea02ca2bd.png)

**Comment by yamamoto-yuta** [comment]
結構めんどくさそう＆解決してもうまみが少ないので，後回しでいいかもですね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
おｋ
条件が分かったらまたお願いします
