### ISSUE TITLE
[preview] CSVファイルをpreviewするときは表っぽく表示する

### ISSUE THREAD

**Issue by yamamoto-yuta** [ShotaroKataoka/Fuzzy-Terminal-Explorer#24]

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
なるほど
![image](https://user-images.githubusercontent.com/42331656/99219366-ce968400-281f-11eb-8dca-48fa12782a0e.png)
columnとか使えるかもね

![image](https://user-images.githubusercontent.com/42331656/99219816-cdb22200-2820-11eb-8a6e-a2e3de84f4de.png)
batcatに拡張子渡すのもアリか

pythonのライブラリだけど
https://github.com/willmcgugan/rich
こういうのもある．これでいろんなファイルをきれいにcatするプログラム作ってもいい

columnは標準で入ってた
batcatはすでに使ってる
richは綺麗だけどインストールが必要（pythonはすでに使ってるのでその点はまあいい）

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
あと多分できないけどpreviewを右・左にスクロールしたいよね？
これってできない？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
CSV以外のファイルはbatcatで十分対応可能かなーと思ったので，CSVだけcolumn適応で良い気はします．
previewの左右スクロールはやりたいですね．調べてみます:+1:

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ちなrich気になったからpipして出力してみた
![image](https://user-images.githubusercontent.com/42331656/99221355-c50f1b00-2823-11eb-82a5-0330650ae181.png)
こんな感じでmarkdownもおしゃになった

weに入れなくてもいいけどrichでおしゃれにcatするコマンドとかあると便利かもなあ（ちら）

**Comment by ShotaroKataoka** [comment]
例のキーバインドのプレビューとかでもいいかも？？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
動作速度等の問題が無ければrichをrequirementsにしてもいいかもですね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
そうすね
requirementsにlsi入ってる時点でわりとあきらめもある
ただlsiはrequirementなしにこだわってrich使わなかった背景もあるからあれ

**Comment by ShotaroKataoka** [comment]
あれか
richでcatするコマンド作ればbatcatは解雇できるから依存の数は変わらないのか

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
今のところrequirementsが
- ls-Improved
- batcat
と既に2つあるので，もうrich入れてしまってもいいかな感はあります

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
python使うならexcelファイルとかwordファイルも読み込めるな．．．（なお速度は不明）

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
https://github.com/junegunn/fzf/issues/1339
横スクロールは無理っぽい

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
まぁEnter押して開けばすぐ確認できますし，今まで通りbatcatでやるか，columnで折り返し禁止にすればひとまず大丈夫な気がします

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
そうっすね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
試しにrichやってみた（gitとかには反映させてない）
![image](https://user-images.githubusercontent.com/42331656/99229519-79fc0480-2831-11eb-8eba-204cdd1cf210.png)

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
良い感じですね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
![image](https://user-images.githubusercontent.com/42331656/99256320-92334a00-2858-11eb-9649-cc9e5e727dcd.png)
一応目標達成プルリクしたら閉じるね
